from tkinter import*
def check():
    print(user_value.get())
    print(pass_value_value.get())
root= Tk()
root.geometry("635x333")
root.title("Security")
user=Label(root,text="Username",fg="white",bg="red",borderwidth=5,relief='sunken')
password=Label(root,text="Password",fg="white",bg="red",borderwidth=5,relief='sunken')
user.grid()
password.grid(row=1)
user_value=StringVar()
pass_value_value=StringVar()
user_entry= Entry(root,textvariable=user_value)
pas_entry=Entry(root,textvariable=pass_value_value)
user_entry.grid(row=0,column=1)
pas_entry.grid(row=1,column=1)
Button(text="Enter",fg="white",bg="black",borderwidth=5,relief='groove',command=check).grid(row=5,column=5)
root.mainloop()