from tkinter import *
root = Tk()
root.geometry("400x400")
root.maxsize(400,400)
root.minsize(400,400)
root.title("Office Management Screen")
#Creating Labels
F_name = Label(root,fg='black',text="First Name")
L_name = Label(root,fg='black',text="Last Name")
A_emp = Label(root,fg ='black',text='Age')
Gend_emp = Label(root,fg='black',text="Gender")
d_oin = Label(root,fg='black',text = "Date of Joining")
deg_k = Label(root,fg='black',text='Post')
earn_k = Label(root,fg='black',text='Salary')
ph_k = Label(root,fg='black',text='Contact Number')
mail_k = Label(root,fg='black',text='Mail Id')
#packing Labels
F_name.grid(ipady=3)
L_name.grid(row=1,column=0,ipady=3)
A_emp.grid(row=1+1,column=0,ipady=3)
Gend_emp.grid(row=3,column=0,ipady=3)
d_oin.grid(row=3+1,column=0,ipady=3)
deg_k.grid(row=5,column=0,ipady=3)
earn_k.grid(row=6,column=0,ipady=3)
ph_k.grid(row=7,column=0,ipady=3)
mail_k.grid(row=8,column=0,ipady=3)
#creating vars 
F_name_value = StringVar()
L_name_value = StringVar()
A_emp_value = StringVar()
Gend_emp_value = StringVar()
d_oin_value = StringVar()
deg_k_value = StringVar()
earn_k_value = StringVar()
ph_k_value = StringVar()
mail_k_value = StringVar()

# Entry value widget
F_name_entry = Entry(textvariable=F_name_value)
L_name_entry = Entry(textvariable=L_name_value)
A_emp_entry  = Entry(textvariable=A_emp_value)
Gend_emp_entry = Entry(textvariable=Gend_emp_value)
d_oin_entry = Entry(textvariable=d_oin_value)
deg_k_entry = Entry(textvariable=deg_k_value)
earn_k_entry = Entry(textvariable=earn_k_value)
ph_k_entry = Entry(textvariable=ph_k_value)
mail_k_entry = Entry(textvariable=ph_k_value)
#packing Entry widget
F_name_entry.grid(row=0,column=1,pady=3,padx=3)
L_name_entry.grid(row=1,column=1,padx=3,pady=3)
A_emp_entry.grid(row=2,column=1,padx=3,pady=3)
Gend_emp_entry.grid(row=3,column=1,padx=3,pady=3)
d_oin_entry.grid(row=4,column=1,padx=3,pady=3)
deg_k_entry.grid(row=4,)
root.mainloop()