from tkinter import *
def check():
    print(userentry.get())
    print(passrentry.get())
root = Tk()
root.geometry("635x333")
root.title("Security")
password = Label(text="Password",bg="black",fg="yellow",borderwidth=6,relief='solid')
user = Label(text="Username",bg="black",fg="yellow",relief='raised',borderwidth=6)
user.grid()
password.grid(row=1)
uservalue = StringVar()
passvalue= StringVar()
userentry=Entry(textvariable=uservalue)
passrentry=Entry(textvariable=passvalue)
userentry.grid(row=0,column=1)
passrentry.grid(row=1,column=1)
Button(text="Submit",fg='yellow',bg="black",borderwidth=6,relief='flat',command=check).grid(row=2,column=2)
root.mainloop()